#!/bin/sh

/usr/bin/invoke_app "$@"    -t classiqs \
                            -C "start_jupyter -A -T @tool main.ipynb" \
                            -r none \
                            -w headless \
                            -u anaconda-6
